### ISSUE TITLE
remove `cypress`

### ISSUE THREAD

**Issue by psimk** [mubanjs/muban#16]
I don't see the reason for having `cypress` or any other E2E testing for a library such as Muban.

E2E testing is used to test the implementation code written by the user of the library. Examples include, multiple network services interacting with one another or an SPA with interacting UI with components passing properties and handling events. These tests are concerned with seeing if any of the interacting services break, not if something within an service is going wrong.

Unit testing is used to test individual _units_ of logic. A simple example would be testing if an `isNumber` function returns `true` when the passed value is indeed a number. These tests are the opposite of E2E, they are never concerned with anything more than the function or class that is being tested.

Lastly, unit testing promotes code separation, which is important for a library as separated code is easier to work with an change in the future.

**Comment by ThaNarie** [comment]
> I don't see the reason for having cypress or any other E2E testing for a library such as Muban.

I do :)

While unit testing should do most of the work, it's hard to cover all cases. So how do you know when you have missed test cases? By people using the components in the wild.

Instead of relying on users to run into "integration" issues and reporting them as bugs, I'd rather test some of the most common or complex component interactions using e2e tests as well, to see if we're missing things that should be covered in unit tests. With a browser, using existing HTML, and actually seeing what happens.

Frameworks like Vue also do this; https://github.com/vuejs/vue/tree/dev/test/e2e/specs

And these e2e tests could also double as
* Examples on how to use muban components
* An example on how e2e tests can be set up inside your own projects

**Comment by psimk** [comment]
Okay, let's keep it as it seems that it would be helpful in immediate testing
